sudo: required

services:
  - docker

language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew check --stacktrace
  - ./gradlew test integrationTest dockerBuildImage cucumber

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libaio1

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
    - ./gradlew jacocoTestReport coveralls