version: '3'
services:

  skeleton-db:
    image: mongo:3.7.9-jessie
    container_name: skeleton-db

  skeleton-app:
    image: skeleton-app
    container_name: skeleton-app
    ports:
      - 8095:8080
    environment:
      - SERVER_PORT=8080
      - MONGO_HOST=skeleton-db
      - MONGO_PORT=27017
      - MONGO_DATABASE=skeleton-db
    depends_on:
      - skeleton-db